# Action Details
name: Issue Milestoned
description: This GitHub Action automatically demilestones an issue immediately after it is milestoned ensuring adherence to the repository policy of having no milestoned issues
author: LFD Systems

# Define your inputs here
inputs:
  GITHUBTOKEN:
    description: The GitHub Personal Access Token
    default: ${{ github.token }}
    required: true

# Define your outputs here.

# Runs On
runs:
  using: node20
  main: dist/index.js
