# Action Details
name: Issue Unpinned
description: This GitHub Action inserts a comment when an issue is automatically unpinned informing about the repository policy of having no pinned issues
author: LFD Systems

# Define your inputs here
inputs:
  GITHUBTOKEN:
    description: The GitHub Personal Access Token
    default: ${{ github.token }}
    required: true

# Define your outputs here.

# Runs On
runs:
  using: node20
  main: dist/index.js
